repos:
  # 基础代码质量检查
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=500]
      - id: check-docstring-first
      - id: debug-statements
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix=lf]

  # Python 代码格式化
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3.11
        args: [--line-length=100, --target-version=py311]
        files: ^(agraph/|tests/|main\.py).*\.py$

  # Import 排序
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [
          "--profile", "black",
          "--line-length=100",
          "--multi-line=3",
          "--trailing-comma",
          "--force-grid-wrap=0",
          "--combine-as"
        ]
        files: ^(agraph/|tests/|main\.py).*\.py$

  # 代码风格和语法检查
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: [
          "--max-line-length=100",
          "--extend-ignore=E203,W503,E501",
          "--per-file-ignores=__init__.py:F401",
          "--max-complexity=10"
        ]
        files: ^(agraph/|tests/|main\.py).*\.py$

  # 类型检查
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        additional_dependencies: [
          pydantic>=2.11.7,
          python-dotenv>=1.0.0,
          openai>=1.99.9,
          types-requests
        ]
        args: [
          "--ignore-missing-imports",
          "--disallow-untyped-defs",
          "--warn-return-any",
          "--warn-unused-configs",
          "--python-version=3.11"
        ]
        files: ^agraph/.*\.py$

  # Pylint 代码质量检查
  - repo: https://github.com/pycqa/pylint
    rev: v3.2.6
    hooks:
      - id: pylint
        additional_dependencies: [
          pydantic>=2.11.7,
          python-dotenv>=1.0.0,
          openai>=1.99.9
        ]
        args: [
          "--max-line-length=100",
          "--disable=missing-module-docstring,missing-class-docstring,missing-function-docstring,too-few-public-methods,too-many-arguments,too-many-instance-attributes,fixme,no-member",
          "--exit-zero"
        ]
        files: ^agraph/.*\.py$

  # 安全检查
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args: ["-f", "json"]
        files: ^agraph/.*\.py$

  # 文档字符串检查
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args: [
          "--convention=google",
          "--add-ignore=D100,D101,D102,D104,D105,D106,D107,D200,D203,D212,D213,D406,D407,D413"
        ]
        files: ^agraph/.*\.py$

  # YAML 格式检查
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [-d, relaxed]
        files: \.(yaml|yml)$

  # Markdown 格式检查
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint
        args: [--fix]
        files: \.md$
